version: '3'
services:
  master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"

  worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://master:7077
    depends_on:
      - master

  spark_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - master